# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moclaw < Formula
  desc "CLI for MoClaw — AI-native ticket management platform with agent orchestration"
  homepage "https://github.com/enmotech/moclaw"
  version "2.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.2/moclaw_v2.1.2_darwin_amd64.tar.gz"
      sha256 "1128cd6cd4281a114ca405acf8c019087d3794a8dc4ce0b6e810e6e58422beb7"

      define_method(:install) do
        bin.install "moclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.2/moclaw_v2.1.2_darwin_arm64.tar.gz"
      sha256 "d440be7e09ace4e94eaa1b79a1cd0b41207b7dfd4bb78550aa4235c397545ffa"

      define_method(:install) do
        bin.install "moclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.2/moclaw_v2.1.2_linux_amd64.tar.gz"
      sha256 "69b5eac950775a2a8e48e967931338c8e202bc59a0a2e18056bef0efbfd73964"
      define_method(:install) do
        bin.install "moclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.2/moclaw_v2.1.2_linux_arm64.tar.gz"
      sha256 "669d3a032e53a08c28542fd51a0715de71a684ba42ddc75755f49df4b192bacd"
      define_method(:install) do
        bin.install "moclaw"
      end
    end
  end
end
