# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moclaw < Formula
  desc "CLI for MoClaw — AI-native ticket management platform with agent orchestration"
  homepage "https://github.com/enmotech/moclaw"
  version "2.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.3/moclaw_v2.1.3_darwin_amd64.tar.gz"
      sha256 "6b61704e427a0c2f4cd4f692c734b6aab99d12ea83d05beff114f11119858064"

      define_method(:install) do
        bin.install "moclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.3/moclaw_v2.1.3_darwin_arm64.tar.gz"
      sha256 "f1208356e7e336807d2f4c8628845ed4a7825bbdbbb793de253e3de52481c426"

      define_method(:install) do
        bin.install "moclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.3/moclaw_v2.1.3_linux_amd64.tar.gz"
      sha256 "35a110eb20296a1ebb09285c3667f892aa97fe4562d2095f29dbf575779158fd"
      define_method(:install) do
        bin.install "moclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.3/moclaw_v2.1.3_linux_arm64.tar.gz"
      sha256 "47f004ea483642371cf0eae332c118648e89616f184d7cae1e5b3202ffed849a"
      define_method(:install) do
        bin.install "moclaw"
      end
    end
  end
end
