# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moclaw < Formula
  desc "CLI for MoClaw — AI-native ticket management platform with agent orchestration"
  homepage "https://github.com/enmotech/moclaw"
  version "2.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.1/moclaw_v2.1.1_darwin_amd64.tar.gz"
      sha256 "ca82b52e9079a0535317664def1abdf98b265ba111613127a3322b51e757d532"

      define_method(:install) do
        bin.install "moclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.1/moclaw_v2.1.1_darwin_arm64.tar.gz"
      sha256 "28cf64bdcb689ff4dcc1b534d6204d18287cfaa1179b9ff7e873d241df802f87"

      define_method(:install) do
        bin.install "moclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.1/moclaw_v2.1.1_linux_amd64.tar.gz"
      sha256 "f7690d33cc5c3656dca15c512430923605385dcda8c74c9a87911c153c589e77"
      define_method(:install) do
        bin.install "moclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/moclaw/releases/download/v2.1.1/moclaw_v2.1.1_linux_arm64.tar.gz"
      sha256 "1041a1792e799b33bc4b6493de9a59c8afdfe98da65fcd03d5803ae2e4d19106"
      define_method(:install) do
        bin.install "moclaw"
      end
    end
  end
end
