# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mopheus < Formula
  desc "CLI for Mopheus — AI-native ticket management platform with agent orchestration"
  homepage "https://github.com/enmotech/mopheus"
  version "2.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/mopheus/releases/download/v2.2.1/mopheus_v2.2.1_darwin_amd64.tar.gz"
      sha256 "c1962d281a6a2343d6ed8697f2b30182e6007ed81a6155a41767e3508b16291e"

      define_method(:install) do
        bin.install "mopheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/mopheus/releases/download/v2.2.1/mopheus_v2.2.1_darwin_arm64.tar.gz"
      sha256 "1952ed81dabf1967b658188267103f3c096c8a4e16c623d4d7d8bd611d75e555"

      define_method(:install) do
        bin.install "mopheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/mopheus/releases/download/v2.2.1/mopheus_v2.2.1_linux_amd64.tar.gz"
      sha256 "a7bc1004aca5fe04e9a039e8b4df00092da09cbd0578ae03571291fd555bed5b"
      define_method(:install) do
        bin.install "mopheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/mopheus/releases/download/v2.2.1/mopheus_v2.2.1_linux_arm64.tar.gz"
      sha256 "0a3dd8214fd58c5ce50c407353cb86ded9ccda3a0b563fb3919db64bdb002263"
      define_method(:install) do
        bin.install "mopheus"
      end
    end
  end
end
