# This file was generated by GoReleaser. DO NOT EDIT.
cask "moclaw" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "258f5e74ea8b159c43fd06a9871d39ab2dac0035549edf82326999e6d1eae155"
      url "https://github.com/enmotech/moclaw/releases/download/v#{version}/moclaw_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01b8b2f84eca92d24b8ae887cb3ea0a23517a58ee1700631c3d095059cf2f68d"
      url "https://github.com/enmotech/moclaw/releases/download/v#{version}/moclaw_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36cac4148baf98bc2c3213a2f1594f4c3f77f98abf86591439d30b86e56f72de"
      url "https://github.com/enmotech/moclaw/releases/download/v#{version}/moclaw_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "65cd9b83f86f1c90049dc0f3fe5fbb059de6d2f50e1f57e8641b9876257c6eea"
      url "https://github.com/enmotech/moclaw/releases/download/v#{version}/moclaw_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "moclaw"
  desc "CLI for MoClaw — AI-native ticket management platform with agent orchestration"
  homepage "https://github.com/enmotech/moclaw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moclaw"

  # No zap stanza required

end
