# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Momem < Formula
  desc "CLI-first memory distillation and retrieval tool for DBA operations knowledge"
  homepage "https://github.com/enmotech/momem-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.0/momem-0.1.0-macOS-amd64.zip"
      sha256 "77c631f58b16377c44fda4e5958b190171f7faba5928e23a7ffb6e6f2d04e513"

      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.0/momem-0.1.0-macOS-arm64.zip"
      sha256 "9dd6b0473a7a208e9a445efb66757646118f182cd1ba2050df4fe42e0c66cd55"

      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.0/momem-0.1.0-linux-amd64.zip"
      sha256 "19f567786768336cb73029b8190a659ab489faa40ab2b19a2cbf21de4bff5377"
      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.0/momem-0.1.0-linux-arm64.zip"
      sha256 "5589bb9ac4e481d4054bda2ff3d1a14951a15c038f80d4fc8b59b2435abadfb2"
      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
  end

  test do
    system "#{bin}/momem", "--version"
  end
end
