# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Momem < Formula
  desc "CLI-first memory distillation and retrieval tool for DBA operations knowledge"
  homepage "https://github.com/enmotech/momem-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.2/momem-0.1.2-macOS-amd64.zip"
      sha256 "f4c47c0e0c03d475a5d9768b93d2866c1baf197f66703190ad5637c5783c3339"

      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.2/momem-0.1.2-macOS-arm64.zip"
      sha256 "0261707a2e819ce6ae1cd3388573ddbabdb7ac004e90be75563e89d6adc5bbc9"

      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.2/momem-0.1.2-linux-amd64.zip"
      sha256 "4aadc02457df83b48f3e95e34adbb3fba5b5c4042007fecb66ac476d2d6b0e38"
      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/momem-cli/releases/download/v0.1.2/momem-0.1.2-linux-arm64.zip"
      sha256 "27c8a9baf87b27a5091756340ca4e3c1efdfc78a5db498e078761f56c59a0a31"
      define_method(:install) do
        bin.install "bin/momem"
        prefix.install "skills"
      end
    end
  end

  test do
    system "#{bin}/momem", "--version"
  end
end
