# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/enmotech/multica"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/multica/releases/download/v1.0.2/multica-cli-1.0.2-darwin-amd64.tar.gz"
      sha256 "1e4e5aaa553abbf017bd5ad4944af0664fb6a0ff0093cf2748a1227c18a6a761"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/multica/releases/download/v1.0.2/multica-cli-1.0.2-darwin-arm64.tar.gz"
      sha256 "fdd0f42e61ea75bf640dac51b6279b6aa3798caaabca8b1cba261a796cff863b"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/multica/releases/download/v1.0.2/multica-cli-1.0.2-linux-amd64.tar.gz"
      sha256 "50b07ac48d5eb8c4335663955a72085281ce79a43d99a4ab7832423d1a4b5473"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/multica/releases/download/v1.0.2/multica-cli-1.0.2-linux-arm64.tar.gz"
      sha256 "36640f2027c85ad5fd91ffdfa9db5e3d6748be30f3ba15113da35619e513713e"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
