# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multica < Formula
  desc "Multica CLI — local agent runtime and management tool for the Multica platform"
  homepage "https://github.com/enmotech/multica"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/multica/releases/download/v1.0.6/multica-cli-1.0.6-darwin-amd64.tar.gz"
      sha256 "52d67f6a59e85356d40e9dff43ad43830f187fb592676dcabfced4eeac14f8b5"

      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/multica/releases/download/v1.0.6/multica-cli-1.0.6-darwin-arm64.tar.gz"
      sha256 "5f988d6a976e16a21d2deb8cf5669640ab8ae4d38775da4662b26d2c8bbee083"

      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/multica/releases/download/v1.0.6/multica-cli-1.0.6-linux-amd64.tar.gz"
      sha256 "c51a52d1e8ed76a38bd3989290f718eaf0ce1996dbed266b022b24a13305fc73"
      define_method(:install) do
        bin.install "multica"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/multica/releases/download/v1.0.6/multica-cli-1.0.6-linux-arm64.tar.gz"
      sha256 "d7cc3fd898163a56b5274ff830a1300a7e95287a7910302ec10dc40c4188ae9d"
      define_method(:install) do
        bin.install "multica"
      end
    end
  end

  test do
    system "#{bin}/multica", "version"
  end
end
