# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssx < Formula
  desc "Retentive ssh client with persistent connection entries"
  homepage "https://github.com/enmotech/ssx"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enmotech/ssx/releases/download/v0.6.1/ssx_v0.6.1_darwin_x86_64.tar.gz"
      sha256 "b7a8e1d2259904b05fd46c6b7d3f95f47dcfa61cdb9cd4f630a316057ebc7565"

      define_method(:install) do
        bin.install "ssx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enmotech/ssx/releases/download/v0.6.1/ssx_v0.6.1_darwin_arm64.tar.gz"
      sha256 "57ae254ee376b3ce85c98b315a9446e2d6b644d94565cb16d73cd73600cdde54"

      define_method(:install) do
        bin.install "ssx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/ssx/releases/download/v0.6.1/ssx_v0.6.1_linux_x86_64.tar.gz"
      sha256 "89dc4ba26fb9e4b0e40d2f00688928cc5d4dd30497f15dec925f1d4285b52dfb"
      define_method(:install) do
        bin.install "ssx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enmotech/ssx/releases/download/v0.6.1/ssx_v0.6.1_linux_arm64.tar.gz"
      sha256 "efc0cd5656a925e973d06cb8e2f895b43f9eaec7b6511a8c5a042a5f94f76432"
      define_method(:install) do
        bin.install "ssx"
      end
    end
  end

  test do
    system "#{bin}/ssx", "--version"
  end
end
